// lib/agents/contracts.ts
// RJA v5.0: Concrete Agent Authority Contracts

import type { AgentAuthorityContract, AgentType } from './types';

export const DISCOVERY_AGENT_CONTRACT: AgentAuthorityContract = {
  agent_id: 'agt-discovery-v1',
  agent_type: 'discovery',
  version: '1.0.0',
  input_sources: ['job_boards', 'ats_feeds', 'career_portals', 'webhooks'],
  evidence_access: 'none',
  allowed_operations: [
    'fetch_raw_listings',
    'canonicalize_urls',
    'normalize_job_schema',
    'extract_requirements',
    'deduplicate_listings',
    'compute_provenance',
    'emit_discovery_proposal',
    'request_further_evaluation',
  ],
  prohibited_operations: [
    'modify_candidate_evidence',
    'read_candidate_profile',
    'draft_application_cover_letter',
    'draft_screening_answers',
    'approve_application',
    'execute_application',
    'alter_fingerprints',
    'forge_provenance',
    'emit_outcome_events',
  ],
  mutable_state_scope: 'none',
  external_actions: ['fetch_public_job_listings'],
  approval_boundary: 'none', // Read-only proposal output; human approval required before application creation
  audit_events: ['agent.discovery.started', 'agent.discovery.completed', 'agent.discovery.duplicate_filtered'],
  failure_behavior: 'fail_closed',
  escalation_path: 'log_and_skip',
};

export const EVALUATION_AGENT_CONTRACT: AgentAuthorityContract = {
  agent_id: 'agt-evaluation-v1',
  agent_type: 'evaluation',
  version: '1.0.0',
  input_sources: ['discovery_proposals', 'candidate_evidence_snapshots'],
  evidence_access: 'snapshot_only',
  allowed_operations: [
    'consume_verified_evidence',
    'consume_canonical_requirements',
    'classify_requirements',
    'identify_evidence_matches',
    'detect_qualification_gaps',
    'attach_evidence_citations',
    'request_additional_review',
    'generate_evaluation_proposal',
    'compute_4d_fit_score',
    'propose_positioning_advice',
  ],
  prohibited_operations: [
    'invent_missing_experience',
    'upgrade_preferred_to_satisfied',
    'mutate_candidate_profile',
    'rewrite_evidence',
    'create_application_artifacts',
    'approve_application_package',
    'sign_human_review_gate',
    'execute_application',
    'alter_deterministic_score',
    'fabricate_unverified_credentials',
    'conceal_qualification_gaps',
    'mutate_execution_receipts',
  ],
  mutable_state_scope: 'ephemeral_proposal',
  external_actions: [],
  approval_boundary: 'none',
  audit_events: ['agent.evaluation.started', 'agent.evaluation.completed'],
  failure_behavior: 'fail_closed',
  escalation_path: 'escalate_to_human_reviewer',
};

export const PLANNING_AGENT_CONTRACT: AgentAuthorityContract = {
  agent_id: 'agt-planning-v1',
  agent_type: 'planning',
  version: '1.0.0',
  input_sources: ['evaluated_opportunities', 'candidate_pacing_preferences'],
  evidence_access: 'snapshot_only',
  allowed_operations: [
    'consume_evaluation_proposals',
    'group_evaluated_opportunities',
    'prioritize_application_preparation',
    'identify_missing_prerequisites',
    'detect_conflicting_dependencies',
    'propose_application_sequence',
    'produce_deterministic_plan',
    'preserve_upstream_provenance',
    'request_human_review',
  ],
  prohibited_operations: [
    'modify_candidate_evidence',
    'modify_evaluation_results',
    'change_fit_scores',
    'mark_job_approved',
    'create_executable_artifacts',
    'sign_human_approval',
    'dispatch_application',
    'modify_outcome_history',
    'contact_external_employers',
    'bypass_human_review',
    'alter_submission_receipts',
  ],
  mutable_state_scope: 'ephemeral_proposal',
  external_actions: [],
  approval_boundary: 'none',
  audit_events: ['agent.planning.started', 'agent.planning.scheduled'],
  failure_behavior: 'fail_closed',
  escalation_path: 'escalate_to_candidate',
};

export const ORCHESTRATOR_AGENT_CONTRACT: AgentAuthorityContract = {
  agent_id: 'agt-orchestrator-v1',
  agent_type: 'orchestrator',
  version: '1.0.0',
  input_sources: ['candidate_goals', 'discovery_proposals', 'evaluations', 'plans'],
  evidence_access: 'snapshot_only',
  allowed_operations: [
    'coordinate_sub_agents',
    'correlate_provenance',
    'construct_workspace_proposal',
    'detect_agent_conflicts',
    'detect_stale_proposals',
    'identify_human_decisions',
    'produce_orchestration_proposal',
    'preserve_upstream_provenance',
    'assemble_workspace_draft',
    'invoke_truthfulness_guard',
    'present_proposal_to_human',
  ],
  prohibited_operations: [
    'modify_candidate_evidence',
    'modify_evaluation_scores',
    'modify_planning_decisions',
    'sign_candidate_approval',
    'self_approve_package',
    'create_executable_artifacts',
    'generate_application_artifacts',
    'execute_application_directly',
    'bypass_v4_6_1_substrate',
    'mutate_approved_artifacts',
    'forge_fingerprint_digest',
    'fabricate_outcome_events',
    'alter_outcome_history',
    'bypass_policy_guard',
  ],
  mutable_state_scope: 'workspace_draft',
  external_actions: [],
  approval_boundary: 'mandatory_human_review',
  audit_events: ['agent.orchestration.started', 'agent.orchestration.assembled'],
  failure_behavior: 'fail_closed',
  escalation_path: 'escalate_to_candidate_review_workspace',
};

export const OUTCOME_AGENT_CONTRACT: AgentAuthorityContract = {
  agent_id: 'agt-outcome-v1',
  agent_type: 'outcome',
  version: '1.0.0',
  input_sources: ['execution_receipts', 'frozen_artifacts', 'planning_proposals'],
  evidence_access: 'snapshot_only',
  allowed_operations: [
    'observe_execution_receipt',
    'read_frozen_artifact',
    'classify_outcome_observations',
    'detect_plan_deviations',
    'produce_immutable_outcome_record',
    'correlate_provenance',
  ],
  prohibited_operations: [
    'modify_frozen_artifact',
    'modify_execution_receipt',
    'modify_planning_decisions',
    'modify_evaluation_results',
    'modify_candidate_evidence',
    'modify_historical_proposals',
    'execute_applications',
    'sign_human_approval',
    'alter_outcome_history',
    'bypass_policy_guard',
  ],
  mutable_state_scope: 'none',
  external_actions: [],
  approval_boundary: 'none',
  audit_events: ['agent.outcome.observed', 'agent.outcome.recorded'],
  failure_behavior: 'fail_closed',
  escalation_path: 'escalate_to_human_auditor',
};

export const FEEDBACK_AGENT_CONTRACT: AgentAuthorityContract = {
  agent_id: 'agt-feedback-v1',
  agent_type: 'feedback',
  version: '1.0.0',
  input_sources: ['OutcomeRecord', 'EvidenceSnapshot', 'SubmissionReceipt'],
  evidence_access: 'snapshot_only',
  allowed_operations: [
    'read_immutable_outcome_record',
    'validate_outcome_provenance',
    'derive_feedback_signals',
    'produce_evidence_feedback_record',
    'canonicalize_feedback',
    'correlate_feedback_provenance',
  ],
  prohibited_operations: [
    'modify_evaluation_results',
    'modify_planning_decisions',
    'modify_orchestration_state',
    'modify_policy_decisions',
    'modify_human_approval',
    'modify_frozen_artifact',
    'modify_execution_receipt',
    'modify_historical_outcome',
    'modify_candidate_profile',
    'execute_applications',
    'sign_human_approval',
    'automatic_replanning',
    'bypass_policy_guard',
  ],
  mutable_state_scope: 'none',
  external_actions: [],
  approval_boundary: 'none',
  audit_events: ['agent.feedback.derived', 'agent.feedback.recorded'],
  failure_behavior: 'fail_closed',
  escalation_path: 'escalate_to_human_auditor',
};

export const LEARNING_AGENT_CONTRACT: AgentAuthorityContract = {
  agent_id: 'agt-learning-v1',
  agent_type: 'learning',
  version: '1.0.0',
  input_sources: ['EvidenceFeedbackRecord', 'OutcomeRecord', 'IntelligenceProfile'],
  evidence_access: 'snapshot_only',
  allowed_operations: [
    'read_historical_feedback',
    'detect_recurring_patterns',
    'propose_profile_adaptations',
    'run_regression_checks',
    'canonicalize_learning_proposal',
    'produce_versioned_profile_diff',
  ],
  prohibited_operations: [
    'modify_evaluation_results',
    'modify_planning_decisions',
    'modify_orchestration_state',
    'modify_policy_decisions',
    'modify_human_approval',
    'modify_frozen_artifact',
    'modify_execution_receipt',
    'modify_historical_outcome',
    'modify_historical_feedback',
    'modify_candidate_profile',
    'direct_evaluator_mutation',
    'direct_planner_mutation',
    'direct_discovery_mutation',
    'direct_orchestration_mutation',
    'automatic_profile_activation',
    'execute_applications',
    'sign_human_approval',
    'bypass_policy_guard',
  ],
  mutable_state_scope: 'none',
  external_actions: [],
  approval_boundary: 'mandatory_human_review',
  audit_events: ['agent.learning.proposed', 'agent.learning.regression_tested'],
  failure_behavior: 'fail_closed',
  escalation_path: 'escalate_to_human_auditor',
};

export const EXPERIMENT_AGENT_CONTRACT: AgentAuthorityContract = {
  agent_id: 'agt-experiment-v1',
  agent_type: 'experiment',
  version: '1.0.0',
  input_sources: ['LearningProposal', 'IntelligenceProfile', 'ExperimentDataset'],
  evidence_access: 'read_only',
  allowed_operations: [
    'read_benchmark_dataset',
    'replay_evaluations_side_by_side',
    'compare_profile_behaviors',
    'calculate_experiment_metrics',
    'detect_regressions',
    'canonicalize_experiment_results',
    'emit_experiment_proposal',
  ],
  prohibited_operations: [
    'modify_evaluation_results',
    'modify_planning_decisions',
    'modify_orchestration_state',
    'modify_policy_decisions',
    'modify_human_approval',
    'modify_frozen_artifact',
    'modify_execution_receipt',
    'modify_historical_outcome',
    'modify_historical_feedback',
    'modify_learning_proposal',
    'mutate_benchmark_dataset',
    'direct_evaluator_mutation',
    'direct_planner_mutation',
    'direct_discovery_mutation',
    'direct_orchestration_mutation',
    'automatic_profile_activation',
    'execute_applications',
    'sign_human_approval',
    'bypass_policy_guard',
  ],
  mutable_state_scope: 'none',
  external_actions: [],
  approval_boundary: 'mandatory_human_review',
  audit_events: ['agent.experiment.started', 'agent.experiment.completed'],
  failure_behavior: 'fail_closed',
  escalation_path: 'escalate_to_human_auditor',
};

export const AGENT_AUTHORITY_REGISTRY: Record<AgentType, AgentAuthorityContract> = {
  discovery: DISCOVERY_AGENT_CONTRACT,
  evaluation: EVALUATION_AGENT_CONTRACT,
  planning: PLANNING_AGENT_CONTRACT,
  orchestrator: ORCHESTRATOR_AGENT_CONTRACT,
  outcome: OUTCOME_AGENT_CONTRACT,
  feedback: FEEDBACK_AGENT_CONTRACT,
  learning: LEARNING_AGENT_CONTRACT,
  experiment: EXPERIMENT_AGENT_CONTRACT,
};

